### ISSUE TITLE
[Table 2] table of key schedule permutation might be not full: only first two rows noted.

### ISSUE THREAD

**Issue by TheVice** [BLAKE3-team/BLAKE3-specs#2]
Hello.

Comparing to what I see at [RFC for BLAKE2](https://tools.ietf.org/html/rfc7693), where table with similar role called 'SIGMA', data for BLAKE3 not full at specification.

For another side, something might be missed by me, so addition description about this situation would be nice.
That why no accompanying pull request for this issue exists at this moment.

If it was created it will contain rest of table that can be founded at [Rust](https://github.com/BLAKE3-team/BLAKE3/blob/78e858d0506d6dfa72b5b690cf4203e90af64b8a/src/lib.rs#L94) and [C](https://github.com/BLAKE3-team/BLAKE3/blob/de1458c565aad524386781793e33d64d45577368/c/blake3_impl.h#L68) reference implementations.

```
-    2 & 6 & 3 & 10 & 7 & 0 & 4 & 13 & 1 & 11 & 12 & 5 & 9 & 14 & 15 & 8 \\
+    2 & 6 & 3 & 10 & 7 & 0 & 4 & 13 & 1 & 11 & 12 & 5 & 9 & 14 & 15 & 8 \\ \midrule
+    3 & 4 & 10 & 12 & 13 & 2 & 7 & 14 & 6 & 5 & 9 & 0 & 11 & 15 & 8 & 1 \\ \midrule
+    10 & 7 & 12 & 9 & 14 & 3 & 13 & 15 & 4 & 0 & 11 & 2 & 5 & 8 & 1 & 6 \\ \midrule
+    12 & 13 & 9 & 11 & 15 & 10 & 14 & 8 & 7 & 2 & 5 & 3 & 0 & 1 & 6 & 4 \\ \midrule
+    9 & 14 & 11 & 5 & 8 & 12 & 15 & 1 & 13 & 3 & 0 & 10 & 2 & 6 & 4 & 7 \\ \midrule
+    11 & 15 & 5 & 0 & 1 & 9 & 8 & 6 & 14 & 10 & 2 & 12 & 3 & 4 & 7 & 13 \\
```

![BLAKE3 - Table 2](https://user-images.githubusercontent.com/5098854/73193134-c35c5580-4132-11ea-915a-0bbf54014277.png)

Thank you.

**Comment by oconnor663** [comment]
Only two rows are included, because in BLAKE3 (unlike BLAKE and BLAKE2) all the subsequent rows are just repeated iterations of the same permutation.
